############################################################
#      ____  ______   ____  _____   _____    ______  __    #
#     / __ \/ ____/  / __ )/  _/ | / /   |  / __ \ \/ /    #
#    / /_/ / __/    / __  |/ //  |/ / /| | / /_/ /\  /     #
#   / ____/ /___   / /_/ // // /|  / ___ |/ _, _/ / /      #
#  /_/   /_____/  /_____/___/_/ |_/_/  |_/_/ |_| /_/       #
#                                                          #
############################################################


title:                "PEB SUPPORT"
thaititle:            "บริษัท พีอี ไบนารี่ จำกัด"
email:                support@pebinary.com
description:          "A support website dedicated to our members and clients"
locale:               en-GB
# permalink:            date
excerpt_separator:    <!--more-->
host:                 localhost
port:                 3000
# url:                  http://pephumin.github.io
# baseurl:              /pebinary.net
quiet:                false
verbose:              true
encoding:             utf-8
timezone:             Asia/Bangkok
google_analytics:     UA-82554411-2

markdown:             kramdown
highlighter:          rouge
kramdown:
  input:              GFM
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
  hard_wrap:          false
  footnote_nr:        1
sass:
  sass_dir:           _sass
  style:              compressed

domains:
  main-en:            http://www.pebinary.com
  main-th:            http://www.pebinary.co.th
  support:            http://www.pebinary.net
  member:             http://www.siamsquare.org
  client:             http://www.siamsquare.org/admin

include:
  - _pages

exclude:
  - README.md
  - run
  - .DS_Store
  - Icon?
  - Gemfile
  - Gemfile.lock
  - database.rules.json
  - firebase.json
  - .firebaserc

gems:
  - jekyll-sitemap
  - jekyll-timeago
  # - jekyll-tagging
  # - jekyll-tagging-related_posts

themeblue:            true

compress_html:
  clippings:          []
  comments:           ["<!-- ", " -->"]
  endings:            []
  startings:          []
  blanklines:         true
  profile:            false

jekyll_timeago:
  depth:              1
  today:              "today"
  yesterday:          "yesterday"
  tomorrow:           "tomorrow"
  and:                "and"
  suffix:             "ago"
  prefix:             ""
  suffix_future:      ""
  prefix_future:      "in"
  years:              "years"
  year:               "year"
  months:             "months"
  month:              "month"
  weeks:              "weeks"
  week:               "week"
  days:               "days"
  day:                "day"

collections:

  members:
    output:           true
    permalink:        /:collection/:path.html
    title:            "Support for members"

  clients:
    output:           true
    permalink:        /:collection/:path.html
    title:            "Support for clients"

  # clientsEN:
  #   output:           true
  #   permalink:        /:collection/:path.html
  #   title:            "Support for clients"
  #
  # clientsTH:
  #   output:           true
  #   permalink:        /:collection/:path.html
  #   title:            "บทความช่วยเหลือสำหรับกลุ่มลูกค้า"

defaults:
  -
    scope:
      path:           ""
      type:           "members"
    values:
      layout:         "main"
      section:        "members"
      nav:            "members"
      label:          false
      label-color:    false
      disable:        false
      toc:            false
      published:      true
      author:         "PEB support"
      author-email:   "support@pebinary.com"
      format:         "layout-left"
  -
    scope:
      path:           ""
      type:           "clients"
    values:
      layout:         "main"
      section:        "clients"
      nav:            "clients"
      label:          false
      label-color:    false
      disable:        false
      toc:            false
      published:      true
      author:         "PEB support"
      author-email:   "support@pebinary.com"
      format:         "layout-right"
  # -
  #   scope:
  #     path:           ""
  #     type:           "clientsEN"
  #   values:
  #     layout:         "main-en"
  #     section:        "clients"
  #     nav:            "clients"
  #     label:          false
  #     label-color:    false
  #     disable:        false
  #     toc:            false
  #     published:      true
  #     author:         "PEB support"
  #     author-email:   "support@pebinary.com"
  #     format:         "layout-right"
  # -
  #   scope:
  #     path:           ""
  #     type:           "clientsTH"
  #   values:
  #     layout:         "main-en"
  #     section:        "clients"
  #     nav:            "clients"
  #     label:          false
  #     label-color:    false
  #     disable:        false
  #     toc:            false
  #     published:      true
  #     author:         "PEB support"
  #     author-email:   "support@pebinary.com"
  #     format:         "layout-right"
  -
    scope:
      path:           "_pages"
      type:           "pages"
    values:
      layout:         "index"
      icon:           "university"
      pageformat:     ""
      published:      true
