############################################################
#      ____  ______   ____  _____   _____    ______  __    #
#     / __ \/ ____/  / __ )/  _/ | / /   |  / __ \ \/ /    #
#    / /_/ / __/    / __  |/ //  |/ / /| | / /_/ /\  /     #
#   / ____/ /___   / /_/ // // /|  / ___ |/ _, _/ / /      #
#  /_/   /_____/  /_____/___/_/ |_/_/  |_/_/ |_| /_/       #
#                                                          #
############################################################


title:                "PEB SUPPORT"
thaititle:            "บริษัท พีอี ไบนารี่ จำกัด"
email:                support@pebinary.com
description:          "A support website dedicated to our members and clients"
locale:               en-GB
permalink:            pretty
excerpt_separator:    <!--more-->
host:                 localhost
port:                 3000
#url:                 http://pephumin.github.io
baseurl:              /support.pebinary.com
quiet:                false
verbose:              true
encoding:             utf-8
timezone:             Asia/Bangkok
google_analytics:     UA-82554411-2
themeblue:            true

markdown:             kramdown
highlighter:          rouge
kramdown:
  input:              GFM
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
  hard_wrap:          false
  footnote_nr:        1
# sass:
#   sass_dir:           _sass
#   style:              compressed

domains:
  main-en:            http://www.pebinary.com
  main-th:            http://www.pebinary.co.th
  support-en:
  support-th:         http://support.pebinary.co.th
  member:             http://www.siamsquare.org
  client:             http://www.siamsquare.net

include:
  - _pages

exclude:
  - README.md
  - run
  - .DS_Store
  - Icon?
  - Gemfile
  - Gemfile.lock
  - database.rules.json
  - .firebaserc
  - firebase.json

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-timeago
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout:           archive
  permalinks:
    category:       /:collection/category/:name/
    tag:            /:collection/tag/:name/
  limit:              5

compress_html:
  clippings:          []
  comments:           ["<!-- ", " -->"]
  endings:            []
  startings:          []
  blanklines:         true
  profile:            false

jekyll_timeago:
  depth:              1
  today:              "today"
  yesterday:          "yesterday"
  tomorrow:           "tomorrow"
  and:                "and"
  suffix:             "ago"
  prefix:             ""
  suffix_future:      ""
  prefix_future:      "in"
  years:              "years"
  year:               "year"
  months:             "months"
  month:              "month"
  weeks:              "weeks"
  week:               "week"
  days:               "days"
  day:                "day"

collections:

  members:
    output:           true
    permalink:        /:collection/:path.html
    title:            "Support for members"

  clients:
    output:           true
    permalink:        /:collection/:path.html
    title:            "Support for clients"

defaults:
  -
    scope:
      path:           ""
      type:           "members"
    values:
      layout:         "main-en"
      section:        "members"
      nav:           "members"
      label:          false
      label-color:    false
      disable:        false
      toc:            false
      published:      true
      author:         "helpdesk"
      author-email:   "support@pebinary.com"
      format:         "layout-left"
  -
    scope:
      path:           ""
      type:           "clients"
    values:
      layout:         "main-en"
      section:        "clients"
      nav:            "clients"
      label:          false
      label-color:    false
      disable:        false
      toc:            false
      published:      true
      author:         "helpdesk"
      author-email:   "support@pebinary.com"
      format:         "layout-left"
  -
    scope:
      path:           "_pages"
      type:           "pages"
    values:
      layout:         "index-en"
      icon:           "university"
      pageformat:     ""
      published:      true
