############################################################
#      ____  ______   ____  _____   _____    ______  __    #
#     / __ \/ ____/  / __ )/  _/ | / /   |  / __ \ \/ /    #
#    / /_/ / __/    / __  |/ //  |/ / /| | / /_/ /\  /     #
#   / ____/ /___   / /_/ // // /|  / ___ |/ _, _/ / /      #
#  /_/   /_____/  /_____/___/_/ |_/_/  |_/_/ |_| /_/       #
#                                                          #
############################################################


title:                "PE BINARY CO., LTD."
email:                support@pebinary.com
description:          "A support website dedicated to our clients and members"
locale:               en-GB
permalink:            pretty
excerpt_separator:    <!--more-->
host:                 localhost
port:                 3000
#url:                 http://pephumin.github.io
baseurl:              /support.pebinary.com
#paginate:            5
#paginate_path:       /blog/:num/
#permalink:           /blog/:year/:month/:day/:title
encoding:             utf-8
timezone:             Asia/Bangkok
google_analytics:     UA-82554411-2

markdown:             kramdown
highlighter:          rouge
#highlighter:         pygments

kramdown:
  input:              GFM

domains:
  main-en:            http://www.pebinary.com
  main-th:            http://www.pebinary.co.th
  client:             http://www.siamsquare.net
  member:             http://www.siamsquare.org
  support:            http://support.pebinary.com

exclude:
  - README.md
  - run
  - .DS_Store
  - Icon?
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-timeago
  - jekyll-archives
  #- jekyll-geo-pattern

#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layout: archive
#  permalinks:
#    category: /blog/category/:name/
#    tag: /blog/tag/:name/

compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  endings: []
  startings: []
  blanklines: true
  profile: false

#jekyll_timeago:
#  depth: 1
#  today: 'today'
#  yesterday: 'yesterday'
#  tomorrow: 'tomorrow'
#  and: 'and'
#  suffix: 'ago'
#  prefix: ''
#  suffix_future: ''
#  prefix_future: 'in'
#  years: 'years'
#  year: 'year'
#  months: 'months'
#  month: 'month'
#  weeks: 'weeks'
#  week: 'week'
#  days: 'days'
#  day: 'day'
